const types = {
	PRODUCTSHOW: 'PRODUCTSHOW',
	PRODUCT_ADD_CART: 'PRODUCT_ADD_CARD',
	PRODUCT_REMOVE_FORM_CART: 'PRODUCT_REMOVE_FROM_CART',
	PRODUCT_REMOVE_ONE_FORM_CART: 'PRODUCT_REMOVE_ONE_FORM_CART',
}

export default types;